### ISSUE TITLE
Cannot close `mdxJsxTextTag` on seemingly valid JSX

### ISSUE THREAD

**Issue by jlengstorf** [toastdotdev/toast-tools#19]
### Subject of the issue

I ran into an error with MDX where a CodePen iframe seems to fail, despite being (as far as I can tell) valid JSX 

I upgraded the Toast MDX package and started seeing this error:
```
Error: Cannot close `mdxJsxTextTag` (160:5-160:9): a different token (`paragraph`, 159:7-162:49) is open
```

diff showing the JSX that failed and the changes I made to remove the error
https://github.com/learnwithjason/learnwithjason.dev/commit/1ce264f4aa862e47af1124bbc645951bf3be97e3

here’s my package info:
https://github.com/learnwithjason/learnwithjason.dev/blob/main/package.json#L27

**Comment by ChristopherBiscardi** [comment]
the mdx core packages have undergone a lot of change since this (and a lot of it at the time was breaking changes), so this should be resolved with the new toast-tools releases.
