### ISSUE TITLE
module '@mdx-js/mdx' does not provide an export named 'default'

### ISSUE THREAD

**Issue by ajstrand** [toastdotdev/toast-tools#23]
I just tried building/running my toast site locally and received this error in my terminal:

> file:///home/alex/Documents/projects/personal-site/node_modules/@toastdotdev/mdx/index.js:1
> import mdx from "@mdx-js/mdx";
>        ^^^
> SyntaxError: The requested module '@mdx-js/mdx' does not provide an export named 'default'
>     at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
>     at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
>     at async Promise.all (index 0)
>     at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
>     at async main (file:///home/alex/Documents/projects/personal-site/node_modules/toast/toast-source-data.mjs:9:15)

It seems like the error is confined to the Toast tools repo.  

I'll try digging into this error and see if I can reproduce on an empty(new) toast project. 

For reference I'm using node 16.13.0.

**Comment by talves** [comment]
I Don't think there is a default export in the @mdx-js/mdx library.
https://github.com/mdx-js/mdx/tree/main/packages/mdx#api

Could you try:
`import * as mdx from "@mdx-js/mdx"`

Nevermind that is coming from the Toast package. It's a breaking change in the mdx library.

**Comment by ChristopherBiscardi** [comment]
I'm going to see if I can reproduce with the starters, but in the meantime can you let me know what version of @mdx-js/mdx you have installed?

**Comment by ChristopherBiscardi** [comment]
I wasn't able to reproduce it tonight, but my hunch is that it's related to the new 2.0-rc.1 release. The version that toast-tools/mdx was written against was 2.0-next.9, so it's likely we need to make a couple updates.

Will try again tomorrow and see if I can upgrade my personal site to see what's going to have to change.

**Comment by ajstrand** [comment]
My mdxjs version is 1.6.22, which is the latest stable version AFAIK.

**Comment by ChristopherBiscardi** [comment]
the current version of toast-tools/mdx requires next.9. What version of toast-tools/mdx are you on?

https://github.com/toastdotdev/toast-tools/blob/63280b8ff8769a700bd0f691af950302f68d059c/packages/mdx/package.json#L12

**Comment by ajstrand** [comment]
Here's my toast-tools/mdx version   `  "@toastdotdev/mdx": "0.2.4",`.

Should i upgrade my ` "@mdx-js/mdx"` version to `"^2.0.0-next.9"` as well?

**Comment by ajstrand** [comment]
@ChristopherBiscardi i was able to reproduce this with the default starter. 

In the index.js file of the toast-tools/mdx package I was able to narrow down the error to this issue:

```bash
{
  filepath: 'content/a-post.mdx',
  remarkPlugins: [ [ [Function: remarkPluckMeta], [Object] ] ],
  rehypePlugins: [
    [ [Function: rehypePrismMdx], [Object] ],
    [Function: slug],
    [ [Function: autolink], [Object] ]
  ]
}
Error: `options.filepath` is no longer supported. Please see <https://mdxjs.com/migrating/v2/> for more information
    at createProcessor (file:///home/alex/Documents/projects/test-repo/node_modules/@mdx-js/mdx/lib/core.js:71:13)
    at compileMdx (file:///home/alex/Documents/projects/test-repo/node_modules/@toastdotdev/mdx/index.js:216:20)
    at processMdx (file:///home/alex/Documents/projects/test-repo/node_modules/@toastdotdev/mdx/index.js:39:10)
    at file:///home/alex/Documents/projects/test-repo/node_modules/@toastdotdev/mdx/index.js:114:24
    at Array.map (<anonymous>)
    at sourceMdx (file:///home/alex/Documents/projects/test-repo/node_modules/@toastdotdev/mdx/index.js:111:11)
    at async Module.sourceData (file:///home/alex/Documents/projects/test-repo/toast.js:4:3)
    at async main (file:///home/alex/Documents/projects/test-repo/node_modules/toast/toast-source-data.mjs:12:5)
node:internal/process/promises:227
        triggerUncaughtException(err, true /* fromPromise */);
```

I replaced the createCompiler function from MDX with this line
`  const compiler = createProcessor(options);`

and i changed the import to `import {createProcessor} from "@mdx-js/mdx";`


the migrations docs dont seem to be written yet 😢

**Comment by ChristopherBiscardi** [comment]
what versions of the libraries are you using there? the mdx-js/mdx 2.0 rc?

**Comment by ajstrand** [comment]
Toast tools is using `   "@mdx-js/mdx": "^2.0.0-next.9",` 
I am running the latest version @toastdotdev/mdx which is "0.2.4"

**Comment by ChristopherBiscardi** [comment]
I just reproduced it in the default starter. You *must* be using `@mdx-js/mdx@2.0.0-rc.1` because that's the only way this error pops up. `2.0.0-next.9` works as expected when using 

```
npx create-toast here
cd here
npm i
npm run build
```

We need to update toast-tools/mdx before it can be used with 2.0.0-rc.1

**Comment by ajstrand** [comment]
So you were partially right, i was pulling in a wrong version of mdx-js/mdx. Im pretty sure I tried using the rc.1 version the other day and that got cached somehow. To get my site to build, I had to pin these resolutions

```json
  "resolutions": {
    "@mdx-js/mdx": "2.0.0-next.9",
    "@mdx-js/preact": "2.0.0-next.8"
  },

```

and I had to specify those exact dependencies too:

```json
    "@mdx-js/mdx": "2.0.0-next.9",
    "@mdx-js/preact": "2.0.0-next.8"

```

it's odd that even though I switched away from that version(2.0.0-rc.1) to 2.0.0-next.9 that node tried to build with that version, when I specified "2.0.0-next.9"(before I added the resolution block which resolved the issue)

**Comment by ChristopherBiscardi** [comment]
yeah, strange indeed. We should try to get your changes implemented and shipped soon to track the rc release

**Comment by ajstrand** [comment]
Here's the gist i made of changes in index.js of toastdotdev/mdx
https://gist.github.com/ajstrand/5870294d6352c30bc5a36d5cd5ef34c5

the code could probably use some cleanup. Until we know what the replacement is for option.filepath, this code wont actually work.

**Comment by ChristopherBiscardi** [comment]
much appreciated 🙏 I'll take a look at it
